require:
  - rubocop-rspec

AllCops:
  NewCops: disable
  # The target Ruby version must match the one in stytch.gemspec.
  TargetRubyVersion: 2.7

Layout/LineLength: { Enabled: false }
LeadingCommentSpace: { Enabled: false }

Metrics: { Enabled: false }

Style/Documentation: { Enabled: false }
Style/For: { Enabled: false }
Style/FrozenStringLiteralComment: { Enabled: false }
Style/NumericPredicate: { Enabled: false }
Style/StringConcatenation: { Enabled: false }

RSpec/DescribedClass: { Enabled: false }
RSpec/ExampleLength: { Enabled: false }
RSpec/MultipleExpectations: { Enabled: false }
