# frozen_string_literal: true

# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!

require_relative 'request_helper'

module StytchB2B
  class RBAC
    include Stytch::RequestHelper

    def initialize(connection)
      @connection = connection
    end

    def policy
      query_params = {}
      request = request_with_query_params('/v1/b2b/rbac/policy', query_params)
      get_request(request)
    end
  end
end
