name: Publish RubyGem and GitHub release

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish RubyGem and GitHub release
    steps:
      - uses: actions/checkout@v3

      - name: Get version
        id: version
        run: |
          VERSION=$(sed -n 's/.*VERSION = "\(.*\)".*/\1/p' lib/stytch/version.rb)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "release_tag=v$VERSION" >> $GITHUB_OUTPUT

      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: Check for config.rb diff
        id: diff
        run: |
          FOUND=0
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ $changed_file == "lib/stytch/version.rb" ]]; then
              FOUND=1
            fi
          done
          echo "diff=$FOUND" >> $GITHUB_OUTPUT

      - name: Create release draft
        if: steps.diff.outputs.diff != 0
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.release_tag }}
          release_name: ${{ steps.version.outputs.release_tag }}
          draft: true
