name: Ruby
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby:
          # Start at the minimum required Ruby version in the gemspec.
          - '2.7'
          - '3.0'
          - '3.1'

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          # Match the minimum supported Ruby version in the gemspec.
          ruby-version: '2.7'
          bundler-cache: true

      - run: bundle exec rubocop
